### ISSUE TITLE
Error response from daemon: denied when trying to pull package from ghcr.io

### ISSUE THREAD

**Issue by sanderbaas** [VROOM-Project/vroom-docker#79] opened 2024-01-24 13:54 UTC
I have create a personal access token (legacy) with `read:packages` permission.

Then I login with docker:
`echo <personal-access-token> | docker login ghcr.io -u <username> --password-stdin`
This replies: `Login Succeeded`

Then I try to pull vroom-docker
`docker pull ghcr.io/vroom-project/vroom-docker:v1.14.0`
This replies: `Error response from daemon: denied`

What am I doing wrong? Or does this have nothing to do with this repo, but with my token?

**Comment by nilsnolde** [comment] 2024-01-24 15:16
you shouldn't need to login at all. what happens if you do `docker logout` and try to pull?

actually IIRC packages on github might be `private` by default and @jcoupey might have to enable them to be `public`. can you have a look at https://github.com/VROOM-Project/vroom-docker/pkgs/container/vroom-docker, there's somewhere settings hidden, I don't have the permissions.  it's at least not even downloaded just once, which is pretty suspicious. why can we even see its existence if it's not public though..

**Comment by sanderbaas** [comment] 2024-01-24 15:27
@nilsnolde when I logout and try to pull I get: `Error response from daemon: Head "https://ghcr.io/v2/vroom-project/vroom-docker/manifests/v1.14.0": unauthorized`. For the link you provided I get a 404 error.

**Comment by nilsnolde** [comment] 2024-01-24 15:30
jep cool, then I have permissions to see the package myself (since I'm the maintainer of this repo I guess). which confirms it's marked as private and @jcoupey has to update it to be public.

**Comment by jcoupey** [comment] 2024-01-24 19:40
I can confirm that the Package visibility is set to private at https://github.com/orgs/VROOM-Project/packages/container/vroom-docker/settings ; the problem being I can't change that (below Public it says " Setting is disabled by organization administrators. "). I tried manually unchecking "Inherit access from source repository " or fiddling with other areas, to no avail.

**Comment by nemosmithasf** [comment] 2024-01-25 04:15
I'm getting the same error. Just to double check, is migrating from the older version with Docker Compose just a matter of changing the image name (once it goes public)

```

version: "2.4"
services:
  vroom:
    ports:
      - 4999:3000
    image: vroomvrp/vroom-docker:v1.11.0  # <<< Chaning this to ghcr.io/vroom-project/vroom-docker:v1.14.0
    container_name: vroom
    volumes:
      - ./vroom/:/conf
    environment:
      - VROOM_ROUTER=osrm  # router to use, osrm, valhalla or ors
    depends_on:
      - osrm_car
      - osrm_bike
      - osrm_foot

  # EXAMPLE for OSRM, please consult the repo for details: https://hub.docker.com/r/osrm/osrm-backend/
  osrm_car:
    image: osrm/osrm-backend
    container_name: osrm_car
    restart: always
    ports:
      - 5000
    volumes:
      - ./osrm/osrm_car:/data
      - ./:/source
    command:  bash -c "
      port=5000
      && source /source/osrm/runOSRM.sh"
    
    
  osrm_bike:
    image: osrm/osrm-backend
    container_name: osrm_bike
    restart: always
    ports:
      - 5001
    volumes:
      - ./osrm/osrm_bike:/data
      - ./:/source
    command: bash -c "
      port=5001
      && source /source/osrm/runOSRM.sh"

  osrm_foot:
    image: osrm/osrm-backend
    container_name: osrm_foot
    restart: always
    ports:
      - 5002
    volumes:
      - ./osrm/osrm_foot:/data
      - ./:/source
    command: bash -c "
      port=5002
      && source /source/osrm/runOSRM.sh"
      
```

**Comment by jcoupey** [comment] 2024-01-30 20:09
OK, [turns out](https://docs.github.com/en/packages/learn-github-packages/configuring-a-packages-access-control-and-visibility#package-creation-visibility-for-organization-members) I had to first go to the package settings at *organization* level to enable the possibility of creating public packages and not only private ones. Then when looking at the specific package settings it was possible to make the switch.

So AFAICT anyone should be able to access now?

**Comment by nemosmithasf** [comment] 2024-02-01 02:36
Can confirm this is fixed

**Closed** 2024-02-01 09:20 UTC
